FROM node:13.12.0-alpine as buider

RUN mkdir -p /app

WORKDIR /app

COPY . .

COPY package*.json ./

RUN npm i
RUN npm cache clean --force
RUN npm install -g @angular/cli@11.2.11
# RUN node --max-old-space-size=8192 node_modules/@angular/cli/bin/ng build

# nginx
# FROM nginx:alpine
# COPY nginx/nginx.conf /etc/nginx/conf/default.conf
# COPY app/dist/pizza-shop usr/share/nginx/html




